version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /mnt/elasticsearch2/data:/usr/share/elasticsearch/data
      - /mnt/elasticsearch2/logs:/usr/share/elasticsearch/logs
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
    networks:
      - elk

  elasticsearch_slaver1:
    build:
      context: elasticsearch_slaver1/
    volumes:
      - ./elasticsearch_slaver1/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /mnt/elasticsearch2/data:/usr/share/elasticsearch/data
      - /mnt/elasticsearch2/logs:/usr/share/elasticsearch/logs
    links:
      - elasticsearch_master
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
    networks:
      - elk
  elasticsearch_slaver2:
    build:
      context: elasticsearch_slaver2/
    volumes:
      - ./elasticsearch_slaver2/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /mnt/elasticsearch2/data:/usr/share/elasticsearch/data
      - /mnt/elasticsearch2/logs:/usr/share/elasticsearch/logs
    links:
      - elasticsearch_master
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
    networks:
      - elk

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/patterns:/usr/local/logstash/patterns
    ports:
      - "5000:5000"
      - "0.0.0.0:5044:5044"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
  redis:
    image: redis:latest
    ports:
      - "0.0.0.0:6379:6379"

  nginx:
    image: nginx:latest
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d

networks:
  elk:
    driver: bridge
